version: 2
jobs:
  build:
    docker:
      - image: node:6.10.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependancies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
          - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
